"""Registry of the Acts in the corpus.

Section titles for the gazette prints (DPDP, CPA) live in the page margins and
come out of PDF extraction scrambled, so they are curated here. RTI titles are
parsed inline from the text.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Act:
    id: str
    name: str
    short: str
    pdf: str
    source_url: str
    num_sections: int
    titles: dict[str, str] = field(default_factory=dict)


DPDP_TITLES = [
    "Short title and commencement",
    "Definitions",
    "Application of Act",
    "Grounds for processing personal data",
    "Notice",
    "Consent",
    "Certain legitimate uses",
    "General obligations of Data Fiduciary",
    "Processing of personal data of children",
    "Additional obligations of Significant Data Fiduciary",
    "Right to access information about personal data",
    "Right to correction and erasure of personal data",
    "Right of grievance redressal",
    "Right to nominate",
    "Duties of Data Principal",
    "Processing of personal data outside India",
    "Exemptions",
    "Establishment of Board",
    "Composition and qualifications for appointment of Chairperson and Members",
    "Salary, allowances payable to and term of office",
    "Disqualifications for appointment and continuation as Chairperson and Members of Board",
    "Resignation by Members and filling of vacancy",
    "Proceedings of Board",
    "Officers and employees of Board",
    "Members and officers to be public servants",
    "Powers of Chairperson",
    "Powers and functions of Board",
    "Procedure to be followed by Board",
    "Appeal to Appellate Tribunal",
    "Orders passed by Appellate Tribunal to be executable as decree",
    "Alternate dispute resolution",
    "Voluntary undertaking",
    "Penalties",
    "Crediting sums realised by way of penalties to Consolidated Fund of India",
    "Protection of action taken in good faith",
    "Power to call for information",
    "Power of Central Government to issue directions",
    "Consistency with other laws",
    "Bar of jurisdiction",
    "Power to make rules",
    "Laying of rules and certain notifications",
    "Power to amend Schedule",
    "Power to remove difficulties",
    "Amendments to certain Acts",
]

CPA_TITLES = [
    "Short title, extent, commencement and application",
    "Definitions",
    "Central Consumer Protection Council",
    "Procedure for meetings of Central Council",
    "Objects of Central Council",
    "State Consumer Protection Councils",
    "Objects of State Council",
    "District Consumer Protection Council",
    "Objects of District Council",
    "Establishment of Central Consumer Protection Authority",
    "Qualifications, method of recruitment, etc., of Chief Commissioner and Commissioners",
    "Vacancy, etc., not to invalidate proceedings of Central Authority",
    "Appointment of officers, experts, professionals and other employees of Central Authority",
    "Procedure of Central Authority",
    "Investigation Wing",
    "Power of District Collector",
    "Complaints to authorities",
    "Powers and functions of Central Authority",
    "Power of Central Authority to refer matter for investigation or to other Regulator",
    "Power of Central Authority to recall goods, etc.",
    "Power of Central Authority to issue directions and penalties against false or misleading advertisements",
    "Search and seizure",
    "Designation of any statutory authority or body to function as Central Authority",
    "Appeal",
    "Grants by Central Government",
    "Accounts and audit",
    "Furnishing of annual reports, etc.",
    "Establishment of District Consumer Disputes Redressal Commission",
    "Qualifications, etc., of President and members of District Commission",
    "Salaries, allowances and other terms and conditions of service of President and members of District Commission",
    "Transitional provision",
    "Vacancy in office of member of District Commission",
    "Officers and other employees of District Commission",
    "Jurisdiction of District Commission",
    "Manner in which complaint shall be made",
    "Proceedings before District Commission",
    "Reference to mediation",
    "Procedure on admission of complaint",
    "Findings of District Commission",
    "Review by District Commission in certain cases",
    "Appeal against order of District Commission",
    "Establishment of State Consumer Disputes Redressal Commission",
    "Qualifications, etc., of President and members of State Commission",
    "Salaries, allowances and other terms and conditions of service of President and members of State Commission",
    "Transitional provision",
    "Officers and employees of State Commission",
    "Jurisdiction of State Commission",
    "Transfer of cases",
    "Procedure applicable to State Commission",
    "Review by State Commission in certain cases",
    "Appeal to National Commission",
    "Hearing of appeal",
    "Establishment of National Consumer Disputes Redressal Commission",
    "Composition of National Commission",
    "Qualifications, etc., of President and members of National Commission",
    "Transitional provision",
    "Other officers and employees of National Commission",
    "Jurisdiction of National Commission",
    "Procedure applicable to National Commission",
    "Review by National Commission in certain cases",
    "Power to set aside ex parte orders",
    "Transfer of cases",
    "Vacancy in office of President of National Commission",
    "Vacancies or defects in appointment not to invalidate orders",
    "Service of notice, etc.",
    "Experts to assist National Commission or State Commission",
    "Appeal against order of National Commission",
    "Finality of orders",
    "Limitation period",
    "Administrative control",
    "Enforcement of orders of District Commission, State Commission and National Commission",
    "Penalty for non-compliance of order",
    "Appeal against order passed under section 72",
    "Establishment of consumer mediation cell",
    "Empanelment of mediators",
    "Nomination of mediators from panel",
    "Duty of mediator to disclose certain facts",
    "Replacement of mediator in certain cases",
    "Procedure for mediation",
    "Settlement through mediation",
    "Recording settlement and passing of order",
    "Application of Chapter",
    "Product liability action",
    "Liability of product manufacturer",
    "Liability of product service provider",
    "Liability of product sellers",
    "Exceptions to product liability action",
    "Penalty for non-compliance of direction of Central Authority",
    "Punishment for false or misleading advertisement",
    "Punishment for manufacturing for sale or storing, selling or distributing or importing products containing adulterant",
    "Punishment for manufacturing for sale or for storing or selling or distributing or importing spurious goods",
    "Cognizance of offence by court",
    "Vexatious search",
    "Measures to prevent unfair trade practices in e-commerce, direct selling, etc.",
    "Presidents, members, Chief Commissioner, Commissioner and certain officers to be public servants",
    "Compounding of offences",
    "Manner of crediting penalty",
    "Protection of action taken in good faith",
    "Power to give directions by Central Government",
    "Act not in derogation of any other law",
    "Power of Central Government to make rules",
    "Power of State Government to make rules",
    "Power of National Commission to make regulations",
    "Power of Central Authority to make regulations",
    "Rules and regulations to be laid before each House of Parliament",
    "Power to remove difficulties",
    "Repeal and savings",
]


def _numbered(titles: list[str]) -> dict[str, str]:
    return {str(i): t for i, t in enumerate(titles, start=1)}


ACTS = [
    Act(
        id="dpdp",
        name="The Digital Personal Data Protection Act, 2023",
        short="DPDP Act, 2023",
        pdf="dpdp_2023.pdf",
        source_url="https://www.indiacode.nic.in/handle/123456789/22037",
        num_sections=44,
        titles=_numbered(DPDP_TITLES),
    ),
    Act(
        id="rti",
        name="The Right to Information Act, 2005",
        short="RTI Act, 2005",
        pdf="rti_2005.pdf",
        source_url="https://www.indiacode.nic.in/handle/123456789/2065",
        num_sections=31,
    ),
    Act(
        id="cpa",
        name="The Consumer Protection Act, 2019",
        short="Consumer Protection Act, 2019",
        pdf="cpa_2019.pdf",
        source_url="https://www.indiacode.nic.in/handle/123456789/15256",
        num_sections=107,
        titles=_numbered(CPA_TITLES),
    ),
]

assert len(DPDP_TITLES) == 44 and len(CPA_TITLES) == 107
